import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import Headeer from '../component/header'

import Sidebar from "../component/sidebar"

const Home: NextPage = () => {
  console.log("I am the home page")
  return (
    <div className="">
      <Head>
        <title>Sidebar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headeer />
    </div>
  )
}

export default Home
